.github/workflows/run-test.yaml
py/create_xtce.py
py/set_alarm.py
requirements.txt
scripts/inst_cfg_mdb.sh
xsd/xtce-v1.2.xsd

This PR contains various enhancements for `py/create_xtce.py` and `scripts/inst_cfg_mdb.sh`.
Despite the number of commits, the changes are not that significant. Each commit only has small changes to clearly show how and what I fixed. You can check the details at [this link](https://github.com/spacecubics/scsat1-mcs/pull/15/files).
The main goal is to make `create_xtce.py` more scriptable, meaning that these changes remove implicit file hierarchy or file naming conventions. Everything must now be explicitly specified—no guessing games.
To handle the tedious command-line options caused by this explicitness, we should use a shell script, as we do with `scripts/inst_cfg_mdb.sh`, or a Makefile, which is not yet implemented. We set all options in the script file so that we don't have to …

Enhancements

---

.github/workflows/run-test.yaml
py/tctm/srs3_tc.yaml

Remove spaces from name attributes.  This is invalid with XTCE spec v1.2.
❯ xmllint --noout --schema xtce-v1.2.xsd mdb/scsat1_main.xml
mdb/scsat1_srs3.xml:1093: element BinaryArgumentType: Schemas
validity error : Element
'{http://www.omg.org/spec/XTCE/20180204}BinaryArgumentType',
attribute 'name': [facet 'pattern'] The value 'SRS-3 RX group
data__command_id' is not accepted by the pattern '[^./:\[\] ]+'.

tctm: srs3_tc: Remove spaces from attribute name

---

py/tctm/adcs_tm.yaml
py/tctm/main_tm.yaml

Currently, we are using only the 1-byte telemetry ID located after the CSP header to differentiate between telemetry from MAIN and ADCS. However, if we start the satctrl used for SRS-3 with the same CSP ID as MAIN or ADCS, there is a risk of misjudgment if, by coincidence, the same telemetry ID matches the data received in Yamcs. Therefore, this commit adds the CSP port number to help differentiate the telemetry for MAIN and ADCS.

tctm: Add CSP port number for telemetry condition

---

py/create_xtce.py

This commit resolves F401 and F841 warnings detected by flake8.
F401 'pathlib.Path' imported but unused
F841 local variable 'tm' is assigned to but never used
F841 local variable 'tc' is assigned to but never used

py: Remove F401 and F841 warnings

---

py/tctm/main_tm.yaml

The telemetry ID parameter name for the MAIN Board uses hyphens, so updates it to underscores to match the other parameter names.

tctm: Fix parameter name for MAIN telemetry ID

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

This commit add the erase command for Config NOR flash and adds the reply telemetry.

tctm: Add erase command for Config NOR flash

---

py/tctm/adcs_tm.yaml

This commit fixes the conditions of reply telemetry for ADCS remove file command.

tctm: Fix conditions for ADCS reply telemetry

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

This command adds a power cycle command for the MAIN/ADCS board and reply telemetry. The power cycle is requested to the TRCH via the FPGA.

tctm: Add power cycle command for MAIN/ADCS

---

py/tctm/adcs_tc.yaml
py/tctm/main_tc.yaml

This commit adds a command to obtain System HK telemetry from the MAIN and ADCS boards in one shot.

tctm: Add one shot System HK command

---

py/tctm/adcs_tm.yaml

This commit fixes the parameter name of the RW temperature sensor.

tctm: Fix parameter name for ADCS RW temp

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

This commit adds a command to clear the boot count stored in FRAM. This command is primarily intended to be executed during testing and right before launch. In addition, it also adds telemetry for reply.

tctm: Add clear boot count command

---

py/tctm/eps_tm.yaml

The bit order of the EPS General telemetry OUTPUT_CONV_STATUS parameter was incorrect, so it has been corrected from little endian to big endian.

tctm: Fix bit order of OUTPUT_CONV_STATUS

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

This commit adds an option to the File info command to calculate the CRC32 value. Since CRC32 calculation may take a long time for larger files, this update enables users to toggle the option on or off when executing the command.

Add CRC32 option to FILE INFO command

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

This commit adds an erase command handler for the NOR flash partition used for data storage.

tctm: Add erase Data NOR command

---

py/tctm/srs3_tc.yaml

Added request packet for Reset of SRS-3 GS Watchdog Timer. However, since reply packets cannot be identified at present, they are displayed as srs3_header.

tctm: Add SRS-3 GS WDT Reset Request

---

py/tctm/eps_tm.yaml
py/tctm/main_tm.yaml

Since there are cases where symbol characters cannot be used by the Yamcs parser, they have been unified to _P/_M.

Rename parameter "+/-" to "_P/_N"

---

py/tctm/zero_tc.yaml
py/tctm/zero_tm.yaml

Adds a command to getting to the temperature of the Payload board via an I2C sensor connected to the Zero. However, the telemetry value in the response is the 16-bit raw data from the sensor (TMP175AQDGKRQ1).

tctm: Add get temperature command for Zero

---

py/tctm/adcs_tc.yaml
py/tctm/main_tc.yaml

Fixes the endian to little for ERASE_CFG_FLASH_CMD on MAIN/ADCS.

tctm: Fix endian for ERASE_CFG_FLASH_CMD

---

py/tctm/adcs_tm.yaml

The 12V VDD will not be used in our initial operations, and the 3V3 DRV, which serves as the power supply for the CV monitor we monitor, will also not be enabled. Therefore, it will be removed from the System HK during the initial operations.

tctm: Remove VDD 12V CV for ADCS System HK

---

py/tctm/eps_tc.yaml
py/tctm/eps_tm.yaml

In FM's EPS General Telemetry, 2-byte parameter has been added compared to EM. Since the Data Packet Stream splits a single General Telemetry into two parts for transmission via CSP packets, the size of one packet has been increased by 1 byte.

tctm: EPS Data Packet Stream supports FM format

---

py/tctm/zero_tc.yaml
py/tctm/zero_tm.yaml

Adds the shell command and reply telemetries for Zero. The commands can accept strings up to 200 bytes in length, and the command responses will be split into 240 byte segments when downlinked. However, to avoid infinite downlinking, a limit is set on the number of responses (50 responses per command).
Additionally, to account for potential command hang-ups, the timeout duration (default:60sec) can also be specified from the Ground.

tctm: Add shell command for Zero

---

py/upload_file.py

Fixes the default directory name on `upload_file.py`.

py: Fix default directory name on upload script

---

py/tctm/zero_tc.yaml
py/tctm/zero_tm.yaml

Adds the get version command for Zero. Currently, it only returns a hard-coded version string.

tctm: Add get version command for Zero

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

Adds a command to read the address of an arbitrary FPGA register and reply telemetry for MAIN/ADCS board.

tctm: Add Read FPGA register command

---

py/tctm/zero_tm.yaml

Adds an error telemetry for file-related commands with invalid sizes or command IDs.

tctm: Add error telemetry for file-related command

---

py/tctm/zero_tm.yaml

Shell command reply telemetry may be divided into multiple telemetries. In such cases, sequence numbers will be assigned to facilitate association.

tctm: Add sequence number for shell cmd reply

---

py/tctm/adcs_tc.yaml
py/tctm/adcs_tm.yaml
py/tctm/main_tc.yaml
py/tctm/main_tm.yaml

Since CRC32 calculation may take time, it might not be completed within an AOS period.
To address this, an API will be added to store the CRC32 calculation result in the FRAM of MAIN/ADCS boards.
The FRAM storage is limited to a single entry, allowing only the result of the last CRC32 calculation to be saved.

Save CRC calculation result to FRAM

---

py/tctm/adcs_tc.yaml
py/tctm/main_tc.yaml

Fix an issue where the command argument offset for FLASH_CFG_ERASE_CMD was incorrect with commit below.
commit 34b3394af365d82f7a6fc6a8024efc7d0a285aeb
Author: Takuya Sasaki <takuya.sasaki@spacecubics.com>
Date:   Sat Nov 23 12:43:03 2024 +0900
tctm: Add CRC save option

tctm: Fix argument offset for Config Memory operations

---

py/tctm/adcs_tc.yaml
py/tctm/main_tc.yaml

Fixes a type of CALC_CRC_CFG_FLASH_CMD.

tctm: Fix typo of CALC_CRC_CFG_FLASH_CMD

---

py/tctm/adcs_tm.yaml
py/tctm/main_tm.yaml

We modified the display format to improve visibility when checking parameter values.

tctm: Change Display Format of CRC32 & Version Parameter to Binary

---

py/tctm/eps_tc.yaml

To make it easier to identify which Channel number corresponds to which power system of SC-Sat1, we changed the display format.

tctm: Modify Channel Selection Display for EPS Single Output Control

---

py/parse_shell_reply.py

Until now, checking shell command replies for the Zero required using the Yamcs web interface. However, replies were divided into multiple parameters, making them difficult to read. This commit adds a tool that consolidates and displays shell replies based on the sequence number assigned to the reply telemetry.

py: Add parse tool for shell command reply

---

py/tctm/eps_tm.yaml

The EPS has a feature to periodically downlink an arbitrary string called a "deploy message." However, there are two issues with the definition of this message:
1. It belongs to the same container as CSP common function
2. EPS adds a non-ASCII value, 0x01, to the first byte of the message
Regarding issue #2, it seems that a 1-byte command ID was intentionally added, similar to other EPS telemetry. However, as a result, the first byte of the `MESSAGE` parameter is not displayed correctly.
This commit fixes the deploy message difinition to belong to the EPS container and adjusts it to recognize the first byte as the command ID.

tctm: Fix EPS deploy message definition

---

etc/security.yaml
etc/users.yaml
etc/yamcs.yaml

This PR enables authentication for Yamcs and allows explicit configuration of the HTTP server's listen address for actual operation. However, the default settings are disabled for the testing environment, so please configure appropriate values for actual operation. .

Add authentication settings

---

INSTALL.org
etc/yamcs.scsat1.yaml
java/pom.xml
java/src/main/java/Scsat1PacketPreprocessor.java

This pull request is a continuation of [Add functionality to modify the Generation Time setting #90](https://github.com/spacecubics/scsat1-mcs/pull/90).
Add functionality to modify the Generation Time setting for Yamcs. The modification can be applied individually based on each telemetry
- Adding files required to create a jar file
- Adding instructions and settings

Add functionality to modify the Generation Time setting

---

.github/workflows/run-test.yaml
.gitlint

Currently, the CI tests for scsat1-mcs install libxml2-util2, but if `apt` index is stale, the installation fail as shown below.
```    
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/
libx/libxml2/libxml2-utils_2.9.14%2bdfsg-1.3ubuntu3.3_amd64.deb
404  Not Found [IP: 52.252.163.49 80]
```
As recommended in the following documentation[1], this commit adds `apt-get update` process before install.
[1]: https://docs.github.com/en/actions/how-tos/manage-runners/github-hosted-runners/customize-runners#installing-software-on-ubuntu-runners

Add apt-get update before package install

---

INSTALL.org
etc/processor.yaml
etc/yamcs.scsat1.yaml
etc/yamcs.yaml
java/pom.xml

Install-related:
- Update installation steps to use Yamcs 5.12.0
- Bump Yamcs dependency version in pom.xml
Config-related (fix warnings):
- Update parameter cache location
- Handle deprecation of provideJvmVariables / provideFsVariables
- Handle deprecation of zeroCopyEnabled

Upgrade Yamcs to 5.12.0 and update configuration

---

INSTALL.org

Updated installation instructions to fix issue with updating yamcs version
- Update install steps to use JDK 17 instead of 11
- The latest Yamcs requirements specify JDK 17 or later.  Accordingly, the installation instructions have been updated.
- Add Maven installation step for Java build
- A Maven install step is added as a build tool for "Implementing additional features" step uses

INSTALL.org: Update Yamcs installation steps for latest version
