spacecubics/scsat1-mcs

INSTALL.org, LICENSE, README.md, README.org, etc/yamcs.yaml, scripts/inst_cfg_mdg.sh
This PR is for add the install procedure.
=> Add install procedure

etc/yamcs.scsat1.yaml
This commit fixes the telecommand definition as below.
- Change protocol from TCP to UDP
- Change UDP port number for telecommand
- Delete post process
=> etc: Fix telecommand definition

.github/workflows/gitlint.yaml, .github/workflows/linelint.yaml
This commit adds the following workflows:
- gitlint
- linelint
=> workflows: Add new workflows

.gitignore, py/alarm/adcs_alarm.yaml, py/alarm/eps_alarm.yaml, py/alarm/main_alarm.yaml, py/alarm/srs3_alarm.yaml, py/set_alarm.py
python set_alarm.py --data YAML_FILE で実行可能
=> Add an alarm for srs3, eps, main, and adcs

.gitignore, py/create_xtce.py, py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml, py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml, py/tctm/header.yaml, py/tctm/main_tc.yaml, py/tctm/main_tm.yaml, py/tctm/srs3_tc.yaml, py/tctm/srs3_tm.yaml
Enable creation of XML files for srs3, eps, main, and adcs
=> Add python script creation of XML files

py/tctm/eps_tm.yaml
This commit fixes the EPS General HK telemetry definitions.
=> py: Fix EPS telemetry definitions

py/create_xtce.py, py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml
This PR adds EPS command (ch output/config ) and response telemetry.
=> Add eps ch config cmd

INSTALL.org
Due to changes in the install script, this commit also updates the documentation.
=> INSTALL.org: Update install procedure

py/alarm/eps_alarm.yaml, py/alarm/main_alarm.yaml, py/tctm/adcs_tm.yaml, py/tctm/eps_tm.yaml, py/tctm/main_tm.yaml, py/tctm/srs3_tm.yaml
This PR has two commits.
1. Remove all trailing white spaces
2. Remove all Japanese characters
=> Remove all Japanese chars

py/tctm/adcs_tm.yaml, py/tctm/main_tm.yaml
This commit revert the wrong PR #25 and re-commit the new commit for add the csp port definition.
=> Fix csp port definition for telemetry

py/tctm/adcs_tc.yaml
This commit adds the shell command for ADCS board.
=> py/tctm: Add shell command for ADCS

py/create_xtce.py
This commit changes the CSP ID for SRS-3 and Yamcs. And sorted it in ascending order.
=> py: Change CSP ID for SRS-3 and Yamcs

py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml, py/tctm/main_tc.yaml, py/tctm/main_tm.yaml
This commit adds definitions for the power control command and its reply telemetry.
=> tctm: Add power control command

py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml, py/tctm/main_tc.yaml, py/tctm/main_tm.yaml
This PR adds a command to retrieve information on files or directories in the data store NOR flash, along with the reply telemetry.
=> Add file info command

py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml, py/tctm/main_tc.yaml, py/tctm/main_tm.yaml
This commit adds the remove file command for MAIN/ADCS and adds the reply telemetry.
=> tctm: Add remove file command

etc/yamcs.scsat1.yaml, py/create_xtce.py, py/tctm/pico_tc.yaml, py/tctm/pico_tm.yaml, scripts/inst_cfg_mdb.sh
PythonによるXML MDB作成用ScriptにPico対応を追加.
=> py: Add support for Raspberry Pi Pico

py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml, py/tctm/srs3_tc.yaml, py/tctm/srs3_tm.yaml
The main changes made to the EPS and SRS-3 yaml files were as follows:
- Added packets
- Modified packet format
- Modified parameter names to unify them
=> Modification of EPS and SRS-3 operating environment

py/create_xtce.py
This commit changes the CSP ID of the Pico to align with actual operations.
=> py: Change CSP ID

etc/yamcs.scsat1.yaml, py/create_xtce.py, py/tctm/zero_tc.yaml, py/tctm/zero_tm.yaml, scripts/inst_cfg_mdb.sh
This PR adds the MDB for Zero.
=> Add zero mdb

py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml, py/tctm/srs3_tm.yaml
My previous update did not include the latest environment and the yamcs environment was broken, so I updated it.
=> Additional corrections to EPS SRS-3 yaml file

py/create_xtce.py
Reflected in ParameterEntry in set_entries_list when offset is set in yaml file.
=> Add offset parameter

py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml
Added request and reply packets for EPS GS Watchdog Timer Clearmark.
=> tctm: Add EPS Deploy Message Telemetry

py/check_upload.py, py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml, py/tctm/main_tc.yaml, py/tctm/main_tm.yaml, py/upload_file.py
This PR adds the OTA related command and telemetries.
- File Upload command and reply telemetries
- Calculate CRC command and reply telemetry
- Copy File to Config NOR flash command and telemetries.
And added the python script for support File upload and check Upload result.
=> OTA support

py/check_upload.py
Adds a `board` option for `check_upload.py`.
=> py: Add board option for check upload result script

py/upload_file.py
Fixes a description on `upload_file.py`.
=> py: Fix description on upload script

py/get_imu_tlm.py, py/tctm/adcs_tc.yaml, py/tctm/adcs_tm.yaml
Adds the IMU telemetry and test tool.
=> Add IMU telemetry and test tool

py/tctm/zero_tc.yaml, py/tctm/zero_tm.yaml, py/upload_file.py
This PR adds the file upload command for Zero and updates the file upload scripts.
=> Add file upload command for Zero

py/tctm/eps_tc.yaml, py/tctm/eps_tm.yaml
The maximum packet size and session duration for EPS file download have been changed.
=> Modify EPS file download packet parameter

py/check/main_check.yaml, py/check_params.py
This PR fixes the issue of parameter check tool.
=> Fix check params tool

services/yamcs.service
This commit adds the necessary systemd service file for Yamcs required for the operation of SC-Sat1.
=> services: Add Yamcs service file

py/eps_history_forward.py, py/mqtt_udp_bridge.py, services/eps_history_forward.service, services/mcs_mqtt_udp_bridge.service
Adding two applications as follows:
1. The proxy app enables data exchange between Leaf Space GS (MQTT) and the Yamcs MCS (UDP).
2. The file download app receives split file data from EPS and reconstructs it to save the files.
=> Adding proxy and file download application

py/create_xtce.py, py/tctm/adcs_tm.yaml, py/tctm/eps_tm.yaml, py/tctm/main_tm.yaml, py/tctm/srs3_tm.yaml, py/tctm/zero_tm.yaml
Make 'base' field in YAML containers mandatory and raise error if missing
Add base field to all containers in YAML (make it mandatory)
=> Require base in yaml
